sudo: false

language: go

go:
  - 1.11.x
  - 1.12.x
  - master

matrix:
  allow_failures:
    - go: master
  fast_finish: true

before_install:
  - go get -t -v ./...

script:
  - diff -u <(echo -n) <(gofmt -d -s .)
  - go vet ./...
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)