package main

import (
	"github.com/gin-contrib/gzip"
	"github.com/gin-gonic/gin"
	"github.com/lloydmeta/todddo-openapi/app"
	"github.com/lloydmeta/todddo-openapi/app/routing"

	// This is generated by swaggo
	_ "github.com/lloydmeta/todddo-openapi/docs"

	"github.com/swaggo/files"
	"github.com/swaggo/gin-swagger"
)

// @title Todo list API
// @version 1.0
// @description A simple Todo list

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html
// @host localhost:8080
// @BasePath /
func main() {
	g := gin.Default()
	components := app.MkDefaultComponents()
	todoRoutesHandler := routing.TodosRoutesHandler{Controller: components.Controllers.TodoController}

	todoRoutesHandler.RegisterRoutes(g)

	g.Use(gzip.Gzip(gzip.BestSpeed))

	// use ginSwagger middleware to serve the API docs
	g.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	if err := g.Run(); err != nil {
		panic(err)
	}
}
